### ISSUE TITLE
Organization Application 2019

### ISSUE THREAD

**Issue by walterbender** [sugarlabs/GSoC#11]
**Why does your org want to participate in Google Summer of Code?**

GSoC is a great opportunity to both broaden the reach of our community, but also a place to take risks on new ideas that could lead to new directions for the program. For example, for the past three years we mentored a project on programming and music that has turned into a major initiative (The Government of Japan is putting Music Blocks into elementary schools as part of its STEM education initiative). GSoC has also been instrumental in helping us reach beyond the desktop onto other platforms, such as Android and Chromium. Plus it is a good way to engage the existing community around these initiatives.

**How many potential mentors have agreed to mentor this year?**

We have 6 so far, but it is early yet in our recruitment process.

**How will you keep mentors engaged with their students?**

We have weekly group meetings of all of the mentors and students and regular individual meetings between mentor teams and students. We use our developer mailing list for GSoC communication so that our developer community is kept abreast of progress and any roadblocks.

**How will you help your students stay on schedule to complete their projects?**

In their proposals, students must present a detailed weekly plan. Each student makes a weekly report at our group meeting. They report what they did, what worked, what didn't, and what is queued up for the next week. This year we will include a weekly report to the developer community as an additional check on student progress.

**How will you get your students involved in your community during GSoC?**

As per above, we conduct all of our meetings in our public IRC channel. Also, students send regular reports to the community as a whole. And students will use git commits and issue tracking in our public repositories (the same as all of out developers). We are also experimenting with some new chat environments (e.g., gitter.im) at the request of some of our newer developers who are less sanguine about IRC.

**How will you keep students involved with your community after GSoC?**

We've continued to have great success in keeping students involved (as mentors in GCI, for example.) Because Sugar is a community project, many of our students do local projects as well. Some former GSoC students are also now GSoC mentors (include one who is a co-admin).

**Has your org been accepted as a mentor org in Google Summer of Code before?**

yes

**What year was your project started?**

2006

**Where does your source code live?**

https://github.com/sugarlabs

**Comment by divyanshu132** [comment]
@walterbender I want to contribute to Sugar Labs as GSOC aspirant, can you please let me know where to get started??

**Comment by quozl** [comment]
Isn't the ideas list enough to get started?  What's wrong with it?

**Comment by pro-panda** [comment]
Application submitted
