### ISSUE TITLE
Suggestion for GSoC 2021: Redesign Human Interface Guidelines and the Sugar UI

### ISSUE THREAD

**Issue by srevinsaju** [sugarlabs/GSoC#112]
It would be nice to have colorful icons for sugar. This is one of the ideas which were not accepted last year into GSoC, for context: https://github.com/sugarlabs/GSoC/blob/master/Ideas-2020.md#colored-desktop-and-activity-icons

**Comment by quozl** [comment]
I agree.  KiCad recently went through an icon recolouring for version 6, and overall it looks better.

**Comment by chimosky** [comment]
I agree and it would be easier if you created a PR for the idea.

**Comment by srevinsaju** [comment]
Cool, I wanted to know y'all opinions (to see if the idea is redundant) before creating the PR. I will create the PR in a while :smile:
