### ISSUE TITLE
Pronunciation Checker Activity

### ISSUE THREAD

**Issue by vaibhavdaren** [sugarlabs/GSoC#12]
Pronunciation Checker

The activity’s main motive is to help a student to learn correct pronunciation. The main idea is to develop an activity which will convert voice into text and match the text with the correctly spelled phonetics which will be available as per word. This text will be as per phonetics rules. The text will then be matched with the correct phonetics already present for the word to be pronounced. The score will be given as per the correctness of the pronounced word. This will help students to learn correct pronunciation as well as phonetics of the word. There can be levels for this activity like words, sentences, paragraph

Open for discussion.

**Comment by pro-panda** [comment]
Thanks, here are my comments;
 - [ ] Do we have language experts for mentoring this?
 - [ ] This looks too less coding for 3 months in terms of building an activity,
 - [ ] I couldn't find tools for scoring based on pronunciation, but I haven't checked thoroughly; do you propose that the student should make his own tool?

**Comment by vaibhavdaren** [comment]
Yes, the student will need to make his own system to get scoring. My idea was to make a match with each alphabet. eg. about phonetics is əbawt. If the speech to text converted for 4 alphabets matches same as out of 5, we can score him 80% correct and highlight the wrongly pronounced alphabet. Suppose the spoken phonetics result is abawt then he will get 80% score.
I myself was working on ML for the last few weeks and I guess @iqraceme might have good experience in this field.

**Comment by pro-panda** [comment]
Thanks,
 - This idea assumes that the student has a microphone facility
 - What will be the tentative size of the trained model that will be embedded in the activity?
 - Are there an open source datasets for this purpose?
 - Do the end users of Sugar Desktop have such a need?
 - This idea assumes that the student speaks in English (if not, then this idea will require more effort than a GSoC Project)

**Comment by quozl** [comment]
> Do the end users of Sugar Desktop have such a need?

I'm struggling to understand how I could teach this subject to the primary school children in our target demographic, but I thought that was just my ignorance in the subject.  Can I see a lesson plan?

> assumes that the student speaks in English

We have previously valued all languages, through our human translation team, and by using iconography instead of text for user interfaces.  At OLPC, most of our devices went to countries that speak Spanish or a derivative.  So I would like to hear how the idea would work for Spanish and other languages.

Assuming a microphone and speaker is okay.

**Comment by vaibhavdaren** [comment]
> What will be the tentative size of the trained model that will be embedded in the activity?
* Being trained model expecting to be of size 400-500 MB.
> Are there an open source datasets for this purpose?
* No, I didn't find any such open source dataset.
> Do the end users of Sugar Desktop have such a need?
* The use of this activity will be for users of all age of students as they will learn how to pronounce properly. There can be different words for different age groups. 
* In various Asian developing countries, children are taught how to speak as per correct phonemes. In our own college and in some of the examination boards of India and especially the ICSC board has a pattern to teach students in class manually through the correct phonemes. This is one of the most important parts of language learning in their course curriculum.

[Curriculum CISCE](http://rajkumaracademy.com/MediaGallery/PreSchoolCurriculum.pdf)

please check at page no. 82 for this course curriculum.
The main purpose of this initiatives are cross cultural communication.
> This idea assumes that the student speaks in English (if not, then this idea will require more effort than a GSoC Project)

Actually phonomes are same for all the languages except there are some which are used in one but not in others.English uses most of the common phonomes

> We have previously valued all languages, through our human translation team, and by using iconography instead of text for user interfaces. At OLPC, most of our devices went to countries that speak Spanish or a derivative. So I would like to hear how the idea would work for Spanish and other languages.

If you reffer the phonology at wikipedia, 

 _Phonology is a branch of linguistics concerned with the systematic organization of sounds in languages. It has traditionally focused largely on the study of the systems of phonemes in particular languages (and therefore used to be also called phonemics, or phonematics), but it may also cover any linguistic analysis either at a level beneath the word (including syllable, onset and rime, articulatory gestures, articulatory features, mora, etc.) or at all levels of language where sound is considered to be structured for conveying linguistic meaning._ 

These Phonetics Inventory of few of the languages:-
1. [English](https://www.asha.org/uploadedFiles/practice/multicultural/EnglishPhonemicInventory.pdf)
2. [French](https://en.wikipedia.org/wiki/French_phonology)
3. [Spanish](https://www.asha.org/uploadedFiles/practice/multicultural/EnglishPhonemicInventory.pdf)

* By seeing these we can see that English and French phonoly is quite similar while spanish differs just a bit. So I was considering it to be an improvement later on by adding other languages. As English being spoken as the as an official languages amoung different countries, I was prefering to start with English and then adding it for other languages.

* Another way for different language issue can be use of google-cloud-speech api which is capable of recogonizing 80 different languages including English, French, Spanish, German etc. . The speech will be recogonized as per language through api and will be evaluated as per its phonomes.
[Google cloud speech api](https://pypi.org/project/google-cloud-speech/)
> I'm struggling to understand how I could teach this subject to the primary school children in our target demographic, but I thought that was just my ignorance in the subject. Can I see a lesson plan?

* Lesson plan:- 
**Level 1**
There will be basic words which will be taught. This will help the student to start pronunciation of some of the daily used words properly.
**Evaluation**
The student will be evaluated on the basis of pronouncing the learned words correctly.
**Level 2**
There will be sentences and some more complex words for practice. This will also improve reading skills of the student.
**Evaluation**
There will be evluation as per the words learned in the new sentences which are not being tought while lesson.
**Level 3**
There will be more complex words, sentences and paragraphs. This will further improve the reading skills of the student.
**Evaluation**
Paragraph reading such as reading a para of a story.
**Level 4**
The knowldege of basic and few complex phonomes of the language will be given to the student. this will help him understnd the different sound for the same words.
**Evaluation**
Testing knowlege of phonomes by phonomes to words or words to phonomes. This test can be objective type.
**Level 5**
The student will be given knowledge of combination of basic phonomes and practicing.
**Final Evaluation**
The student will be tested on all the above critrias which he has learnt.

**Comment by quozl** [comment]
That sounds like a style of mechanised memorisation learning which is somewhat foreign to Sugar Labs.  @walterbender, can you suggest how to modify this lesson plan to better fit with constructivist teaching methods?

**Comment by walterbender** [comment]
I would like to see some activity associated with this Activity that involves some creativity by the students and perhaps some sort of collaboration or interaction between students (taking advantage of Sugar's strengths) and leveraging our pedagogical approach. Maybe combine it with a chat activity where the chat is enabled by proper pronunciation (and perhaps something fun happens in the case that there is mispronunciation). And where the students can also "critique" and support each other?

**Comment by pro-panda** [comment]
Fixed in 5d22851a
