### ISSUE TITLE
Jupyter Notebook activity for Sugar

### ISSUE THREAD

**Issue by quozl** [sugarlabs/GSoC#13]
Fill out an idea; adding an activity to Sugar to provide Jupyter Notebook functionality.

Has been [tested on Ubuntu 16.04.4 in March](http://lists.sugarlabs.org/archive/sugar-devel/2018-March/055189.html).

As a [replacement for Web Confusion](http://lists.sugarlabs.org/archive/sugar-devel/2019-January/056168.html).

A mix of design and user requirements; a Python activity to start the notebook process, identify the port, start an embedded Browse instance against that port, maintain the notebook as a journal object, allow export of other things to journal objects, and cleanly terminate the notebook process on activity stop.  Provide a log button for diagnosing notebook output.  For the bundle and tar.gz distribution, expect downstreams to install the dependencies, and provide an alert if the dependencies are missing.

Expected mentors; 
James Cameron, Rahul Bothra

**Comment by walterbender** [comment]
Tony has expressed an interest in this too and perhaps could provide a group of students for testing.

**Comment by walterbender** [comment]
I think that the Jupyter notebook idea could be fleshed out if it extended to programming examples (and documentation) on how to use the notebook for some interesting projects (especially ones that involve capturing and analyzing data from other activities.)

**Comment by pro-panda** [comment]
Fixed in 5d22851a

**Comment by quozl** [comment]
Jupyter Lab is also very interesting.  John Leeman (also of [Don't Panic Geocast](http://www.dontpanicgeocast.com/)), did a [summary video](https://www.youtube.com/watch?v=xuow8n9xqO0).
