### ISSUE TITLE
GSoC 2022

### ISSUE THREAD

**Issue by ahmadateya** [sugarlabs/GSoC#139]
Will you join the GSoC this year? What about the Ideas list? Is the last year not accepted ideas will be migrated to this year?

**Comment by quozl** [comment]
I have not heard yet.  It will be a decision for the board.

However, that doesn't stop work on the ideas list.  Sometimes not accepted ideas are used, sometimes accepted ideas are used, and sometimes new ideas are made.

**Comment by rodrickcalvin** [comment]
Is anyone working on this? "[Music Blocks Project Blocks Reorganization](https://github.com/sugarlabs/GSoC/blob/master/Ideas-2021.md#music-blocks-project-blocks-reorganization)"? I can take it up

**Comment by chimosky** [comment]
@rodrickcalvin the project you've pointed out was part of last years' ideas and it was an accepted project so it was probably worked on, if you'd like more info you can send an email to the [sugar-devel](https://lists.sugarlabs.org/listinfo/sugar-devel) list asking about the possible ideas for Music Blocks this year.

**Comment by llaske** [comment]
There is now a dedicated page [here](https://github.com/sugarlabs/GSoC/blob/master/Ideas-2022.md).
