### ISSUE TITLE
Point to Gitter?

### ISSUE THREAD

**Issue by pro-panda** [sugarlabs/GSoC#14]
I've reverted the mode of communication back to IRC from Gitter in 899cf71, to ensure consistency.

Should be closed along with https://github.com/sugarlabs/www-sugarlabs/pull/290

**Comment by jaskirat2000** [comment]
"bridge-bot" can be a good idea for this which will kepp posted people everywhere by sending messages from anywhere with a particular channel tag and those can be viewed on any channel which consist of that bot.

**Comment by quozl** [comment]
@jaskirat2000, your post will have been missed by most people in Sugar Labs, so please use the best forum for discussion, the sugar-devel@ mailing list.  See https://github.com/sugarlabs/sugar-docs/blob/master/src/CODE_OF_CONDUCT.md#be-flexible

**Comment by jaskirat2000** [comment]
Okay, thanks
