### ISSUE TITLE
New project idea

### ISSUE THREAD

**Issue by jigyasunigam** [sugarlabs/GSoC#150]
Hey! I have a project idea from a long time ago in my mind. And I think this is right place to bring my idea into a reality.
I want to discuss it with someone associated mentor with sugarlabs.

**Comment by llaske** [comment]
@jigyasunigam I think it's better to suggest your idea as an issue in the matching repo (Sugar, MusicBlocks or Sugarizer) so maintainers could study it.

**Comment by jigyasunigam** [comment]
Ok thank you.
