### ISSUE TITLE
matrix link

### ISSUE THREAD

**Issue by walterbender** [sugarlabs/GSoC#156]
We should make it easier to find our [matrix channel](https://matrix.to/#/#sugar:matrix.org) from this page. (It is obvious from sugar-docs, but not at all obvious here.)

**Comment by chimosky** [comment]
Agreed, I've added a reference to it in [21619de](https://github.com/sugarlabs/GSoC/commit/21619de9ff612e2627a755e05f5da49876acf3e1).
