### ISSUE TITLE
GSoC'23 Contributor Needs 

### ISSUE THREAD

**Issue by sumaiya1996** [sugarlabs/GSoC#158]
Hey All 👋

As a GSOC'23 Contributor I want guides regarding Oppia, FOSDEM, Zulip and Chromium.

**Comment by chimosky** [comment]
> Hey All wave
> 
> As a GSOC'23 Contributor I want guides regarding Oppia, FOSDEM, Zulip and Chromium.

Hi @sumaiya1996, you'll have to go to those org repos and look for their guidelines.

Closing this.
