### ISSUE TITLE
Machine Learning Teaching activity

### ISSUE THREAD

**Issue by iqraceme** [sugarlabs/GSoC#16]
**Idea:** The idea is to create a new sugar activity that would allow kids a chance to learn basic machine learning concepts from the activity. Machine Learning is all about how we can train a computer to learn for itself or to train a computer to recognise images or to train a computer to recognise text.So the activity will be based on a game in which the kids train the computer to be able to sort photos into groups.Students will train a machine learning model to recognise pictures of cars or cups. They will see that the more they train the computer, the more better it becomes to sort a pile of photos into groups.

**Reason for proposing the activity idea:** Kids are being taught the "concept" of ML and AI in summer schools. Its an existing project from the MIT media lab, that I took the idea from. In Korea, teaching kids the basic concepts of AI and ML is already part of the curriculum in their schools. The concept of teaching the basic concept of as AI and ML as part of United kingdom's national school's curriculum is also in the process. Please refer to the links below on a background of how machine learning and AI are being proposed to be adapted in different school's curriculum
[1]  http://dalelane.co.uk/blog/?p=3513
[2]https://teachinglondoncomputing.org/machine-learning/
[3]https://www.media.mit.edu/posts/kids-teach-ai-a-little-humanity-with-cognimates/
[4]https://community.computingatschool.org.uk/resources/5376/single [5]https://www.raconteur.net/technology/ai-in-schools-students-future

**Comment by quozl** [comment]
Something I saw connected.  The AI or ML algorithm should meet our definition of free software we share with our parent organisation, the Software Freedom Conservancy.  See [How to Disappear Completely](https://www.youtube.com/watch?v=LOulCAz4S0M) from linux.conf.au just now, which points out, by about eight minutes in, that several of the ML algorithms for image recognition are proprietary.  The rest of the talk is also interesting.

**Comment by iqraceme** [comment]
Tensor Flow is one of the major examples of open source framework for ML. We can use it for image recognition via their Python API.

https://github.com/tensorflow/tensorflow
https://www.tensorflow.org/

https://towardsdatascience.com/tensorflow-image-recognition-python-api-e35f7d412a70

**Comment by quozl** [comment]
Thanks.

**Comment by pro-panda** [comment]
Fixed in 5d22851a
