### ISSUE TITLE
[FIX] typo in readme

### ISSUE THREAD

**Issue by himanshu1221** [sugarlabs/GSoC#172]
I have fixed the typo in the readme **after mistake, there should be a colon, not a semi-colon**

![Screenshot from 2023-02-24 15-18-57](https://user-images.githubusercontent.com/32031706/221148199-507d5f38-9a6a-429c-8e01-a90f94e9df9b.png)

**Comment by quozl** [comment]
Please don't duplicate effort by creating an issue for a pull request.  Just the pull request was sufficient.  Also, please don't use screenshots of words, copy and paste the words instead.  Otherwise we can never find it by searching history.
