### ISSUE TITLE
spelling error in gsoc documentation

### ISSUE THREAD

**Issue by AkshJain99** [sugarlabs/GSoC#19]
```
Sugar has a lot of activities (250+ on GitHub, and more elsewhere). To understand how to locate and work on activities, see our guide to Modifying Activities. This project expeects you to think of what new activities can be created. The activity / set of activities should add a new learning experience for the user, and should also justify the 3 months timeline for GSoC.
```

**Comment by pro-panda** [comment]
Fixed in b7367fe

**Comment by quozl** [comment]
@AkshJain99, thanks for the fix, but please don't create an issue for something trivial you intend to change.  Just make the pull request.  Thanks.

**Comment by AkshJain99** [comment]
Okay actually just getting familiar with sugar labs work flow :)

**Comment by quozl** [comment]
No worries.  Read about [Work flow](https://github.com/sugarlabs/sugar-docs/blob/master/src/contributing.md#workflow);

> An improvement to Sugar may start with an issue discussion, to build consensus and ensure that work isn't wasted. **An issue may be avoided** for fixing bugs that are obvious to everyone or part of a project.
