### ISSUE TITLE
Project idea for Gsoc 2025

### ISSUE THREAD

**Issue by AliyanA1** [sugarlabs/GSoC#206]
Full Name:
Aliyan

Email and GitHub Username:
    • Email: darkpikayt1@gmail.com
    • GitHub Username: AliyanA1

Project Details:
I propose to develop a Collaboration-Friendly Coding Platform for Sugar Labs that enables children to collaborate in real-time while working on coding projects, such as creating stories or games. The platform will allow kids to join shared coding workspaces, make real-time edits, and interact with each other using integrated chat, voice, or video communication. The platform will leverage simple drag-and-drop code blocks, like those found in Scratch or Blockly, combined with features such as version control, activity logs, and permission-based roles.

The core features include:
    1. Real-Time Collaboration: Multiple users can work on a project simultaneously, seeing each other's changes in real-time.
    2. Interactive Chat and Communication: Integrated messaging and optional voice/video chat to facilitate teamwork.
    3. Version Control & History Tracking: The platform will keep a history of all changes made by users, with an ability to revert to previous versions.
    4. Permissions & Roles: Users can have specific roles (Editor, Viewer) to control access and permissions within the project.
    5. Breakout Sessions: Ability for smaller groups to collaborate within a larger project, enhancing team coordination.
    6. Feedback and Peer Learning: Integrated comments or tags for collaborative problem-solving and peer feedback.
This project will create an interactive, fun, and collaborative space where kids can code together, share ideas, and develop stories and games, encouraging teamwork, peer learning, and social interaction.

How will it impact Sugar Labs?
    • Foster Peer Learning: Enables children to collaborate and learn together, improving coding skills through teamwork and social interaction.
    • Expand Audience Base: Appeals to schools and communities, encouraging group learning and increasing platform adoption.
    • Enhance Social Learning: Promotes communication and cooperation, helping kids develop critical soft skills.
    • Encourage Creativity: Kids can work on complex projects together, sparking innovation through collaboration.
    • Strengthen Sugar Labs’ Position: Positions Sugar Labs as a cutting-edge, collaborative learning tool, attracting more contributors.

The technologies that (programming languages, etc.) will be using
    • Frontend: React.js (UI), Socket.io (real-time communication), Redux/React Context (state management), Konva.js/Fabric.js (canvas interaction).
    • Backend: Node.js with Express (server-side), Firebase (real-time database & authentication), WebRTC (optional peer-to-peer communication).
    • Version Control & Permissions: Simplified version control, role-based access control (Editor/Viewer).

**Comment by quozl** [comment]
Thanks.  As with the issue posted immediately before yours, the next step is for you to identify a Sugar Labs member who is;
* a contributor to one of the Sugar Labs software projects; Sugarizer, Sugar or Music Blocks, and;
* willing to be the Google Summer of Code mentor.

**Comment by chimosky** [comment]
In addition to what has been said, I'll also suggest you use and contribute to our software.

**Comment by AliyanA1** [comment]
Ok Sir

**Comment by AliyanA1** [comment]
Oh, I see! Thank you for pointing that out. In that case, would it be possible for me to contribute to the project in another way, or should I think of a new idea? I'd love to explore how I can best support the initiative.

**Comment by quozl** [comment]
https://help.sugarlabs.org/en/collaborating.html describes collaborating in Sugar.

I'm not sure if Music Blocks offers collaboration.

Thank you for your idea, but it looks like it is already mostly present.

See sugar-docs and sugarizer repositories for further information about contributing.

**Comment by chimosky** [comment]
There's work on [MB](https://github.com/sugarlabs/musicblocks/tree/collaboration) for collaboration that's yet to be deployed.

**Comment by chimosky** [comment]
> Oh, I see! Thank you for pointing that out. In that case, would it be possible for me to contribute to the project in another way, or should I think of a new idea? I'd love to explore how I can best support the initiative.

We have issues open on Github which you're welcome to contribute to, feel free to take a look.
