### ISSUE TITLE
Suggestions for Sugarizer Exerciser activity

### ISSUE THREAD

**Issue by NikhilM98** [sugarlabs/GSoC#47]
I was going through Sugarizer Exerciser code. I have some ideas that can be extended to **Expand Sugarizer Exerciser activity**  idea.

### Improve text translation
Currently text is translated using key value pairs which are hard coded in the project. It limits overall translation capability of the project. New questions created using the activity cannot be translated. I think that language translation API should be integrated in the project so that it could translate questions and answers on users preferance.

### Integrate text to speech
Text to speech API can be integrated so that kids who are not comfortable with reading could understand the question and answers. It would also help in improving the vocabulary of the children and teaching them correct pronunciation of the words.

### Restructure Project
Project structure is quite irregular. Custom webpack confuguration for the react can be implemented instead of using `react-scripts`. It would help in reducing the size of the project. Project dependencies are outdated, they can be updated. Tests for the project are missing.

P.S. @llaske I have already made some [pull requests](https://github.com/llaske/ExerciserReact/pulls) on Exerciser. Can you please take a look at them.

**Comment by llaske** [comment]
Thanks for your proposal.

Regarding **translation** it's not hard coded today. Strings are defined in JSON and translated using a Weblate platform [here](http://translate.sugarizer.org/projects/sugarizer/activity-exerciser/). 

Regarding **text to speech**, adding images support is precisely to handle kids not comfortable with reading. Most/allTtext to speech API are not libre/open source and often need an Internet Connection. It's two important things for Sugarizer.

Regarding **restructure project**, you're free to propose some improvement on it if you can justify that there is good practice not followed in the current implementation.

**Comment by NikhilM98** [comment]
@llaske Thanks for reviewing my suggestion.

I was not saying that there is an issue with the translation of the Exerciser App (The language of the app can be switched smoothly). I mean that the strings for questions and answers is hardcoded. You can see it [here](https://github.com/llaske/ExerciserReact/blob/5a91ddadb2917d429066bb47713dfcc83ebfe66e/src/translations/en.json#L44-L55).


The weblate platform is useful for translating more version of same project. But it cannot translate new questions that will be added by the teachers.
![screenshot from 2019-03-07 20-58-34](https://user-images.githubusercontent.com/24666770/53968483-2446fd80-411d-11e9-9793-ab915a20694a.png)
(Image shows seed question translations)

I agree that even if we use free API, Internet connection would be an issue in the proposed ideas.

**Comment by llaske** [comment]
Ok, you're right. BTW this feature is not expected today. More: it's not always possible to translate an exercise. The sample you've mentioned is a good example: questions in English and in French are not the same.
