### ISSUE TITLE
Missing ideas for Scratch inside Sugar

### ISSUE THREAD

**Issue by quozl** [sugarlabs/GSoC#5]
Scratch-3.0 is based on JavaScript.  Online editor works okay with Browse activity on Sugar.  An offline editor is not yet available for Linux.  There may be an opportunity to collaborate with the Scratch project to make that editor available as a Sugar activity.

@samswag, what's your opinion?

**Comment by samswag** [comment]
Agreed. But the only problem with Scratch 3.0 with Browse is the recording of voice and sounds which is very important. Yes, I have made contact with the Scratch team, basically played around it for months now with testing. 

We had a [GCI task](https://github.com/EmilyOng/Scratch.activity/tree/caf9fa0465cbe96eaa5574d03d78ec3abc49945e) in 2017 to make Scratch 3.0 available for [Sugarizer](https://github.com/llaske/sugarizer/tree/master/activities/Scratch.activity) and possible sugar.

So I think the Gsoc task is to fix the issue with sugar-activity-web enough that we can have Scratch running directly.  

Fork the latest version from scratch, follow Emily guide, build Scratch as Sugar-web activity. But if we still want to use the Browse-Embed we will have to figure out why WebKit isn't supporting record and sound.

I will ping the lead engineer of the Scratch team for possible collaboration to make this happen. I am sure, he will be happy to help and assist.

Those are my opinions.

**Comment by quozl** [comment]
Scratch 3.0 in Browse.  Works.  We can exclude that from GSoC ideas.  Sound playback is fine, but sound recording shows a permissions issue only.  Browse doesn't use `sugar-activity-web`, so it's not part of the [permission problem](https://github.com/sugarlabs/browse-activity/issues/85) in Browse.

Scratch 3.0 in Sugarizer.  Works.  We can exclude that from GSoC ideas.  It is an older Scratch 3.0 though.  Playback is okay.  Recording is not available.  I'm not sure why; perhaps it wasn't available at the time of forking.  @EmilyOng or @llaske may know.

Scratch 3.0 as a native JavaScript activity in Sugar.  Does not exist.  We can include that in GSoC ideas.  Yes, Emily's work may help with that.  `sugar-activity-web` does not handle any of the permissions requests from WebKit.

**Comment by llaske** [comment]
The Scratch 3.0 version in Sugarizer is a beta 3.0 version. It's why some features are not include in it (for example localization). The next Sugarizer release - expected this month - will upgrade the Scratch version but it will not be the "official" 3.0 version.
BTW The Scratch version in Sugarizer integrate two specific features: load/save into the Journal and offline mode (integrate backgrounds, sounds and costumes without Internet connection).
There is a work to upgrade the Scratch version in Sugarizer to the official 3.0 version, but it's not enough work for a GSoC.

**Comment by samswag** [comment]
Well to bring it to Sugar Desktop, not Sugarizer is enough work to Gsoc given that how we classify projects. But again, it is not my duty to say which can be a GSoC project. All I know is that we need a stable version of Scratch running on Sugar. The question is how?

**Comment by quozl** [comment]
@llaske, thanks, good to know.  I agree, upgrading already working Scratch in Sugarizer is not a large enough task for a GSoC project.

@samswag, for Sugar desktop, as I said above, we already have Scratch working in Browse.  A GSoC project could work on Scratch as a native JavaScript activity in Sugar.  `sugar-web` is used by all native JavaScript activities in Sugar, and is already used by Scratch in Sugarizer.

**Comment by pro-panda** [comment]
Fixed in 5d22851a
