### ISSUE TITLE
Define priority for projects

### ISSUE THREAD

**Issue by pro-panda** [sugarlabs/GSoC#52]
See https://github.com/sugarlabs/GSoC/pull/44#issuecomment-469476971

>  - perhaps the priority metadata already in the document isn't being used seriously, in that the board did not decide it, and candidates may misunderstand it;
> - there is a mix of terms (high, medium, moderate), and "high" appears very frequently (50%),
> - it is not clear what the terms mean.

Possible solutions are to remove the priority tag entirely or to review all projects collectively and decide the priorities again.

**Comment by quozl** [comment]
I consent to removing priority.

**Comment by llaske** [comment]
I'm okay to remove priority. I've just added it because it was there in the template.
FYI I've tagged "High priority" projects where there is an explicit request on the field (Dashboard, Exerciser) and "Medium priority" project nice to have but not direct request (Write).

**Comment by walterbender** [comment]
Fine with me.
