### ISSUE TITLE
Add subsection for previous work on related projects in proposal template

### ISSUE THREAD

**Issue by NikhilM98** [sugarlabs/GSoC#57]
I was working on creating a proposal following the proposal [template](https://github.com/sugarlabs/GSoC/blob/master/Template.md).

It's mentioned that:
> Share links, if any, of your previous work on open source projects?

It would be nice to add a similar sub-section to give a brief overview of related projects which are not open source.

**Comment by quozl** [comment]
One of the open source licensing tenets is that looking at source code that is _closed source_, then writing _open source_ code with the closed source in your mind, is legally similar to creating a _derivative work_.  There are clean-room procedures to help avoid that; one team reads the closed source, writes a specification, and another team writes code to comply.  So I for one don't like to look at closed source.  Others may differ.

**Comment by NikhilM98** [comment]
@quozl
Okay, thanks for the feedback. Should I close this issue?

**Comment by quozl** [comment]
Thanks for your thanks.  I decided not to close immediately because although I gave my opinion, I'm not confident we have consensus.  Nothing has changed since except your thanks.  I see no reason to hurry to close.

**Comment by pro-panda** [comment]
> So I for one don't like to look at closed source
+1
