### ISSUE TITLE
Draft proposals

### ISSUE THREAD

**Issue by quozl** [sugarlabs/GSoC#60]
We get proposals as Google Docs links;

* Google Docs is not open source, so this requires everyone to use proprietary software,
* Google Docs can change after the mail is sent, so comments in a thread can age,
* Google Docs can disappear; we've lost the record of proposals from previous years because we haven't kept a copy, and a student has cleaned up their Google Docs or closed their account,
* Google Docs may have the _export_ feature disabled by the author.

Some organisations require specific formats, but we haven't made any requirements.  See [Writing a proposal - Follow the Rules](https://google.github.io/gsocguides/student/writing-a-proposal).

I'm fine with the students using Google Docs, but I'd like the proposals to be PDF or text files.

We have also heard of final proposals submitted to Google Dashboard without any draft proposal or community engagement.

How should we change our guidance here?

**Comment by sum2it** [comment]
Most organisations have a wiki for proposals. Helps in keeping a copy and easily browsing proposals.

**Comment by pro-panda** [comment]
We should ask the students to mail the proposal as a PDF on Sugar-Devel.

**Comment by vaibhavdaren** [comment]
@pro-panda   it is hard to keep track of proposals and students via mailing list . 
any other solution ?

**Comment by pro-panda** [comment]
Sorry, no. I don't have any other solution.

FWIW, I review all the proposals we receive, focusing more on the ones that I am mentoring. The mailing list is convenient enough for me

**Comment by quozl** [comment]
I've encountered a proposal with the _export_ feature turned off by the author.  An interesting trick.
