### ISSUE TITLE
Create New Activity Proposals

### ISSUE THREAD

**Issue by chimosky** [sugarlabs/GSoC#63]
I've looked at the proposals for [create a new set of activities](https://github.com/sugarlabs/GSoC/blob/master/Ideas-2019.md#create-a-new-set-of-activities) and none has addressed any of the activities proposed in the idea, although the project idea encourages new ideas but I think that we should clearly state the importance of the ones suggested as they're very important. 
Scratch for one is very important as it's currently widely used and having it in sugar would mean more users. 

I think that the importance of these ideas should be stated and they shouldn't be neglected as they have.

**Comment by iqraceme** [comment]
The idea of porting scratch to sugar desktop has also been mentioned in "Port Sugarizer activities to Sugar" project idea.

**Comment by pro-panda** [comment]
Discussion continuing on thread http://lists.sugarlabs.org/archive/sugar-devel/2019-April/056632.html. 
Closing to avoid two strands of communication.
