### ISSUE TITLE
Missing channel name in README.md for sugarlab's IRC

### ISSUE THREAD

**Issue by yagyanshbhatia** [sugarlabs/GSoC#7]
The link in the readme is just https://webchat.freenode.net/ , it'd be better if you can tell the channel name too, I did try joining `#SugarLabs` but it seems like its the wrong room as I don't see any conversations there
I'm interested in contributing here for the porting to py3 project, I've already setup the development environment (packaged) and wrote my first activity too. 
If there's another channel, please invite me too! I'm excited to work here :smile: 
@pro-panda

**Comment by pro-panda** [comment]
Thanks for pointing out @yagyanshbhatia.

You can join `#sugar` for the discussions
