### ISSUE TITLE
Google Code-In inquiry   

### ISSUE THREAD

**Issue by Abhay-dot** [sugarlabs/GSoC#71]
Hey, my name is Abhay and I'm 13 years old and I'm currently living In Singapore. I'm really exited to join your organisation and contribute to the Google Code-In.

**Comment by quozl** [comment]
Thanks for asking.  Off-topic for GSoC, and was answered in [a mailing list thread](http://lists.sugarlabs.org/archive/sugar-devel/2019-November/057288.html), so closing.
